USE [master]
GO

/****** Object:  Database [Email_Marketing_DW]    Script Date: 10/13/2019 6:55:59 PM ******/
CREATE DATABASE [Email_Marketing_DW]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Email_Marketing_DW', FILENAME = N'C:\SQL Server\Email_Marketing_DW.mdf' , SIZE = 73728KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Email_Marketing_DW_log', FILENAME = N'C:\SQL Server\Email_Marketing_DW_log.ldf' , SIZE = 335872KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [Email_Marketing_DW] SET COMPATIBILITY_LEVEL = 140
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Email_Marketing_DW].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Email_Marketing_DW] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Email_Marketing_DW] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Email_Marketing_DW] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Email_Marketing_DW] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Email_Marketing_DW] SET ARITHABORT OFF 
GO

ALTER DATABASE [Email_Marketing_DW] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Email_Marketing_DW] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Email_Marketing_DW] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Email_Marketing_DW] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Email_Marketing_DW] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Email_Marketing_DW] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Email_Marketing_DW] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Email_Marketing_DW] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Email_Marketing_DW] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Email_Marketing_DW] SET  ENABLE_BROKER 
GO

ALTER DATABASE [Email_Marketing_DW] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Email_Marketing_DW] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Email_Marketing_DW] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Email_Marketing_DW] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Email_Marketing_DW] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Email_Marketing_DW] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Email_Marketing_DW] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Email_Marketing_DW] SET RECOVERY FULL 
GO

ALTER DATABASE [Email_Marketing_DW] SET  MULTI_USER 
GO

ALTER DATABASE [Email_Marketing_DW] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Email_Marketing_DW] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Email_Marketing_DW] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Email_Marketing_DW] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Email_Marketing_DW] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Email_Marketing_DW] SET QUERY_STORE = OFF
GO

USE [Email_Marketing_DW]
GO

ALTER DATABASE SCOPED CONFIGURATION SET IDENTITY_CACHE = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [Email_Marketing_DW] SET  READ_WRITE 
GO

